[package]
name = "chitu-macros"
authors = ["Lei Zhengyu"]
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
tokio = { version = "1", features = ["full"] }
syn = "2.0"
quote = "1.0"
