

PIPE_DICT = {
    "cons_req": "cons.req.fifo",
    "cons_res": "cons.res.fifo",
    "import_req": "import.req.fifo",
    "import_res": "import.res.fifo",
    "export_req": "export.req.fifo",
    # "export_res": "export.res.fifo",
    "write_req": "write.req.fifo",
    "write_res": "write.res.fifo",
    "read_req": "read.req.fifo",
    "read_res": "read.res.fifo",
    "end_req": "end.req.fifo",
    # "end_res": "end.res.fifo",
    "await_req": "await.req.fifo",
    "await_res": "await.res.fifo",
    # "merge_req": "merge.req.fifo",
    # "merge_res": "merge.res.fifo",
    "trigger_req": "trigger.req.fifo",
    # "trigger_res": "trigger.res.fifo",
    "pdict_write_req": "pdict.write.req.fifo",
    "pdict_write_res": "pdict.write.res.fifo",
    "pdict_await_req": "pdict.await.req.fifo",
    "pdict_await_res": "pdict.await.res.fifo",
}