apiVersion: v1
kind: Service
metadata:
  name: simplest-query-front
  namespace: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
      - protocol: TCP
        port: 16686
        targetPort: 16686
