// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.15.8
// source: pany.proto

package pany

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PAnyReplace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Elem []byte `protobuf:"bytes,2,opt,name=elem,proto3" json:"elem,omitempty"`
}

func (x *PAnyReplace) Reset() {
	*x = PAnyReplace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pany_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAnyReplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAnyReplace) ProtoMessage() {}

func (x *PAnyReplace) ProtoReflect() protoreflect.Message {
	mi := &file_pany_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAnyReplace.ProtoReflect.Descriptor instead.
func (*PAnyReplace) Descriptor() ([]byte, []int) {
	return file_pany_proto_rawDescGZIP(), []int{0}
}

func (x *PAnyReplace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PAnyReplace) GetElem() []byte {
	if x != nil {
		return x.Elem
	}
	return nil
}

type PAnyVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val []byte `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *PAnyVal) Reset() {
	*x = PAnyVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pany_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAnyVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAnyVal) ProtoMessage() {}

func (x *PAnyVal) ProtoReflect() protoreflect.Message {
	mi := &file_pany_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAnyVal.ProtoReflect.Descriptor instead.
func (*PAnyVal) Descriptor() ([]byte, []int) {
	return file_pany_proto_rawDescGZIP(), []int{1}
}

func (x *PAnyVal) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_pany_proto protoreflect.FileDescriptor

var file_pany_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x61,
	0x6e, 0x79, 0x22, 0x31, 0x0a, 0x0b, 0x50, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6c, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x65, 0x6c, 0x65, 0x6d, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x41, 0x6e, 0x79, 0x56, 0x61, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x70, 0x61, 0x6e, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pany_proto_rawDescOnce sync.Once
	file_pany_proto_rawDescData = file_pany_proto_rawDesc
)

func file_pany_proto_rawDescGZIP() []byte {
	file_pany_proto_rawDescOnce.Do(func() {
		file_pany_proto_rawDescData = protoimpl.X.CompressGZIP(file_pany_proto_rawDescData)
	})
	return file_pany_proto_rawDescData
}

var file_pany_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pany_proto_goTypes = []interface{}{
	(*PAnyReplace)(nil), // 0: pany.PAnyReplace
	(*PAnyVal)(nil),     // 1: pany.PAnyVal
}
var file_pany_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pany_proto_init() }
func file_pany_proto_init() {
	if File_pany_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pany_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAnyReplace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pany_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAnyVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pany_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pany_proto_goTypes,
		DependencyIndexes: file_pany_proto_depIdxs,
		MessageInfos:      file_pany_proto_msgTypes,
	}.Build()
	File_pany_proto = out.File
	file_pany_proto_rawDesc = nil
	file_pany_proto_goTypes = nil
	file_pany_proto_depIdxs = nil
}
